config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about' ,as: 'about'
  resources :users, only: [:show,:index,:edit,:update] do
  resource  :relationships, only: [:create, :destroy]
  get 'followings' => 'relationships#followings', as: 'followings'
  get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :books, onl: [:index,:show,:create,:edit,:update,:destroy] do
  resources :book_comments, only: [:create, :destroy]
  resource  :favorites, only: [:create, :destroy]
  end
  get '/search', to: 'searchs#search'
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end 

app/models/book.rb
class Book < ApplicationRecord
  
  	validates :title, presence: true
  	validates :body, presence: true, length: {maximum: 200}
  	validates :rate, presence: true
    validates :rate, numericality: {
    # only_integer: true,
    greater_than_or_equal_to: 1,
  }
  	
  	belongs_to :user
  	has_many :favorites, dependent: :destroy
  	has_many :book_comments, dependent: :destroy
  	
  	
    def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
    end
    # 絞り込機能はじまり
  def self.search_for(content, method)
    if method == 'perfect'
      Book.where(title: content)
    elsif method == 'forward'
      Book.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      Book.where('title LIKE ?', '%'+content)
    else
      Book.where('title LIKE ?', '%'+content+'%')
    end
     # 絞り込機能終わり
  end
  # タグ機能はじまり
  def Book.search(search_word)
    Book.where(['category LIKE ?', "#{search_word}"])
  end
  # タグ機能おわり
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def index
    @books = Book.all.order(params[:sort])
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @user = @book.user
    @book_comment = BookComment.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title,:body,:rate)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr id="book_<%= book.id %>">
        <td><%= link_to user_path(book.user.id) do %>
          <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg" %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td><%= link_to book.category, search_path(keyword: book.category) %></td>
        <!--いいね機能の追加--------------------------------->
          <td class="favorite-btn">
           <%= render 'favorites/favorite-btn', book: book %>
          </td>
          <!--いいね機能の追加-------------------------------->
          <td><%= link_to "#{book.book_comments.count}コメント",book_path(book.id) %></td>
        
          <!--星の評価はじまり-->
          <td>
          <div id="rate_<%= book.id %>"></div>
          <script>
          $('#rate_<%= book.id %>').raty({
            size: 20,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            half: true,
            readOnly: true,
            score: <%= book.rate %>,
          });
          </script>
				  </td>
          <!--星の評価おわり-->
          
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_searchindex.html.erb
<table>
    <thead>
        <tr>
            <th>投稿者名</th>
            <th>タイトル</th>
            <th>本文</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody id="book">
    <% books.each do |book| %>
      <tr>
        <td><%= book.user.name %></td>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to "詳細", book_path(book) %></td>
        <% if post.user == current_user %>
          <td><%= link_to "編集", edit_book_path(book) %></td>
          <td><%= link_to "削除", book_path(book), method: :delete, remote: true %></td>
        <% else %>
          <td></td>
          <td></td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= render 'layouts/errors', obj: @book %>

      <%= form_with model:@book,local:true do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control book_title' %>
        </div>
        <div class="form-group">
          <%= f.label :opinion %>
          <%= f.text_area :body, class: 'form-control book_body' %>
        </div>
      
        <div class="form-group" id="rate_<%= @book.id %>"></div>
        <script>
          $('#rate_<%= @book.id %>').raty({
            size: 20,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            half: true,
            readOnly: true,
            score: <%= @book.rate %>,
          });
        </script>

        <div class="form-group">
          <%= f.submit class: 'btn btn-success' %>
        </div>
      <% end %>

      <%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
      <%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
   <% if @book.errors.any? %>
     <div class="text-danger">
     <h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>
      <ul>
      <% @book.errors.full_messages.each do |message| %>
     <li><%= message %></li>
      <% end %>
      </ul>
       </div>
   <% end %>

  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'users/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= link_to "新しい順", books_path(sort: 'created_at DESC') %> | <%= link_to "評価の高い順", books_path(sort: 'rate DESC') %>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
 <div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info' ,user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'users/form', book: @book_new %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Book detail</h2>
      <table class='table'>
        <tbody>
         <tr id="book_<%= @book.id %>">
          <td><%= link_to user_path(@user.id) do %>
            <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg',fallback: "no-image-icon.jpg" %><br>
            <%= @user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book.id) %></td>
          <td><%= @book.body %></td>
          <!--いいね機能の追加はじまり--------------------------------->
          <td class="favorite-btn"><%= render 'favorites/favorite-btn', book: @book %></td>
          <!--いいね機能の追加おわり-------------------------------->
          <td>コメント数：<%= @book.book_comments.count %></td>
          <!--星の評価はじまり-->
           <td>
            <div id="rate_<%= @book.id %>"></div>
            <script>
              $('#rate_<%= @book.id %>').raty({
                size: 20,
                starOff:  '<%= asset_path('star-off.png') %>',
                starOn : '<%= asset_path('star-on.png') %>',
                starHalf: '<%= asset_path('star-half.png') %>',
                half: true,
                readOnly: true,
                score: <%= @book.rate %>,
              });
            </script>
          </td>
          <!--星の評価終わり-->
          <% if @user == current_user %>
          <td><%= link_to 'Edit', edit_book_path(@book.id), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
          <td><%= link_to 'Destroy', book_path(@book.id), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger "%></td>
          <% end %>
          
        </tr>
        </tbody>
      </table>
      <!--コメント機能------------------------------------->
        <table class="book_comments">
        <%= render 'book_comments/index', book: @book %>
        </table>
          
          <%= form_with model:[@book,@book_comment] do |f| %>
            <%= f.text_area :comment, rows:'5',:size=>"90x5" %>
            <%= f.submit "送信" %>
          <%  end  %>
          
          <!--コメント機能------------------------------------->
    </div>
  </div>
</div>